services:
  api:
    build: .
    container_name: server_tracker-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: server_tracker-db
    restart: always
    environment:
      POSTGRES_USER: alvaro
      POSTGRES_PASSWORD: alva123
      POSTGRES_DB: firs-project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alvaro"]
      interval: 5s
      timeout: 5s
      retries: 5

  admirer:
    image: adminer
    container_name: server_tracker-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
